function makePretty(hFig)
set(findall(hFig,'type','axes'),...
    'FontName','FixedWidth',...
    'FontSize',16,...
    'FontWeight','bold',...
    'Box', 'off',...
    'YGrid','on',...
    'XColor',[.6 .6 .6],...
    'YColor',[.6 .6 .6],...
    'ZColor',[.6 .6 .6]);
set(findall(hFig,'type','text'),...
    'FontName','FixedWidth',...
    'FontSize',20,...
    'Color',[.3 .3 .3])